const books = [
  {
    id: 1,
    title: "Foundation",
    author: "Isaac Asimov",
    category: "Science",
    year: 1951,
    language: "English",
    address: "A2",

    description:
      "A sweeping tale of psychohistory and the rise and fall of galactic empires.",
    cover: "/assets/imgs/bookCovers/OL46125W.jpg",
    price: 1000,
  },
  {
    id: 2,
    title: "Ficciones",
    author: "Jorge Luis Borges",
    category: "Fiction",
    year: 1945,
    language: "English",
    address: "A2",
    description:
      "A mind-bending collection of short stories that blur reality and imagination.",
    cover: "/assets/imgs/bookCovers/OL110971W.jpg",
    price: 550,
  },
  {
    id: 3,
    title: "Dracula",
    author: "Bram Stoker",
    category: "Horror",
    year: 1897,
    language: "English",
    address: "B2",
    description:
      "Gothic horror about the legendary vampire and the hunt to stop him.",
    cover: "/assets/imgs/bookCovers/OL85892W.jpg",
    price: 480,
  },
  {
    id: 4,
    title: "The Last Man",
    author: "Mary Shelley",
    category: "Speculative Fiction",
    year: 1826,
    language: "English",
    address: "B2",
    description:
      "A haunting post-apocalyptic novel exploring loss, civilisation, and survival.",
    cover: "/assets/imgs/bookCovers/OL450124W.jpg",
    price: 420,
  },
  {
    id: 5,
    title: "Beloved",
    author: "Toni Morrison",
    category: "Historical Fiction",
    year: 1987,
    language: "English",
    address: "B2",
    description:
      "A powerful, poetic story about memory, trauma, and the legacy of slavery.",
    cover: "/assets/imgs/bookCovers/OL50548W.jpg",
    price: 760,
  },
  {
    id: 6,
    title: "The Time Machine",
    author: "H. G. Wells",
    category: "Science Fiction",
    year: 1895,
    language: "English",
    address: "C2",
    description:
      "A scientist travels far into the future and witnesses humanity's strange fate.",
    cover: "/assets/imgs/bookCovers/OL52267W.jpg",
    price: 450,
  },
  {
    id: 7,
    title: "The Invisible Man",
    author: "H. G. Wells",
    category: "Science Fiction",
    year: "N/A",
    language: "English",
    address: "C2",
    description:
      "A dark tale of science, isolation, and the consequences of unchecked power.",
    cover: "/assets/imgs/bookCovers/OL52266W.jpg",
    price: 460,
  },
  {
    id: 8,
    title: "Dune",
    author: "Frank Herbert",
    category: "Science Fiction",
    year: 1965,
    language: "English",
    address: "A2",
    description:
      "Epic political and ecological saga set on the desert planet Arrakis.",
    cover: "/assets/imgs/bookCovers/OL893415W.jpg",
    price: 1250,
  },
  {
    id: 9,
    title: "Мы",
    author: "Евгений Иванович Замятин",
    category: "Dystopian",
    year: 1924,
    language: "English",
    address: "C2",
    description:
      "A prescient dystopian vision that examines freedom, conformity, and the state.",
    cover: "/assets/imgs/bookCovers/OL10215W.jpg",
    price: 520,
  },
  {
    id: 10,
    title: "A Room of One's Own",
    author: "Virginia Woolf",
    category: "Essay",
    year: 1929,
    language: "English",
    address: "A2",
    description:
      "An influential essay on women, creativity, and the material conditions for writing.",
    cover: "/assets/imgs/bookCovers/OL39379W.jpg",
    price: 490,
  },
  {
    id: 11,
    title: "The War of the Worlds",
    author: "H. G. Wells",
    category: "Science Fiction",
    year: "N/A",
    language: "English",
    address: "R2",
    description:
      "A classic invasion story of Martian machines and human resistance.",
    cover: "/assets/imgs/bookCovers/OL52114W.jpg",
    price: 530,
  },
  {
    id: 12,
    title: "Kim",
    author: "Rudyard Kipling",
    category: "Adventure",
    year: 1901,
    language: "English",
    address: "E2",
    description:
      "A coming-of-age adventure through the intrigue and landscape of colonial India.",
    cover: "/assets/imgs/bookCovers/OL19908W.jpg",
    price: 470,
  },
  {
    id: 13,
    title: "The Riddle of the Sands",
    author: "Erskine Childers",
    category: "Adventure",
    year: 1903,
    language: "English",
    address: "T2",
    description:
      "A nautical thriller of espionage and danger in the North Sea sands.",
    cover: "/assets/imgs/bookCovers/OL23797W.jpg",
    price: 510,
  },
  {
    id: 14,
    title: "The blue castle",
    author: "Lucy Maud Montgomery",
    category: "Fiction",
    year: 1926,
    language: "English",
    address: "W2",
    description:
      "A warm novel about self-discovery, rebellion, and unexpected love.",
    cover: "/assets/imgs/bookCovers/OL77775W.jpg",
    price: 430,
  },
  {
    id: 15,
    title: "The Scarlet Pimpernel",
    author: "Emmuska Orczy, Baroness Orczy",
    category: "Historical Fiction",
    year: 1900,
    language: "English",
    address: "Q2",
    description:
      "Adventure and daring rescues during the French Revolution, with a masked hero.",
    cover: "/assets/imgs/bookCovers/OL1253285W.jpg",
    price: 500,
  },
  {
    id: 16,
    title: "Flatland",
    author: "Edwin Abbott Abbott",
    category: "Satire",
    year: 1884,
    language: "English",
    address: "G2",
    description:
      "A clever mathematical satire exploring dimensions, society, and perspective.",
    cover: "/assets/imgs/bookCovers/OL118388W.jpg",
    price: 400,
  },
  {
    id: 17,
    title: "The Awakening",
    author: "Kate Chopin",
    category: "Fiction",
    year: 1899,
    language: "English",
    address: "F2",
    description:
      "A landmark novel about independence, desire, and the limits placed on women.",
    cover: "/assets/imgs/bookCovers/OL65430W.jpg",
    price: 440,
  },
  {
    id: 18,
    title: "Dubliners",
    author: "James Joyce",
    category: "Fiction",
    year: 1914,
    language: "English",
    address: "D2",
    description:
      "A linked collection of short stories portraying life in early 20th-century Dublin.",
    cover: "/assets/imgs/bookCovers/OL86320W.jpg",
    price: 610,
  },
  {
    id: 19,
    title: "Of Human Bondage",
    author: "William Somerset Maugham",
    category: "Fiction",
    year: 1915,
    language: "English",
    address: "J2",
    description:
      "A deep exploration of desire, suffering, and the quest for meaning.",
    cover: "/assets/imgs/bookCovers/OL505781W.jpg",
    price: 590,
  },
  {
    id: 20,
    title: "Shirley",
    author: "Charlotte Brontë",
    category: "Fiction",
    year: 1800,
    language: "English",
    address: "D2",
    description:
      "A social novel that examines class conflict, work, and women's roles.",
    cover: "/assets/imgs/bookCovers/OL1095397W.jpg",
    price: 470,
  },
  {
    id: 21,
    title: "The Martian Chronicles",
    author: "Ray Bradbury",
    category: "Science Fiction",
    year: 1950,
    language: "English",
    address: "S2",
    description:
      "A lyrical series of stories about humans colonising Mars and its consequences.",
    cover: "/assets/imgs/bookCovers/OL103134W.jpg",
    price: 720,
  },
  {
    id: 22,
    title: "Lilith",
    author: "George MacDonald",
    category: "Fantasy",
    year: 1895,
    language: "English",
    address: "S2",
    description:
      "A haunting fantasy about redemption, death, and the spirit world.",
    cover: "/assets/imgs/bookCovers/OL15437W.jpg",
    price: 460,
  },
  {
    id: 23,
    title: "The Sign of Four",
    author: "Arthur Conan Doyle",
    category: "Mystery",
    year: 1889,
    language: "English",
    address: "S2",
    description:
      "A classic Sherlock Holmes mystery involving treasure and betrayal.",
    cover: "/assets/imgs/bookCovers/OL262438W.jpg",
    price: 520,
  },
  {
    id: 24,
    title: "Persuasion",
    author: "Jane Austen",
    category: "Romance",
    year: 1789,
    language: "English",
    address: "S2",
    description:
      "A gentle, mature romance about second chances and quiet endurance.",
    cover: "/assets/imgs/bookCovers/OL66544W.jpg",
    price: 560,
  },
  {
    id: 25,
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    category: "Fiction",
    year: 1850,
    language: "English",
    address: "S2",
    description:
      "A moral tale of sin, guilt, and public shame in Puritan New England.",
    cover: "/assets/imgs/bookCovers/OL455305W.jpg",
    price: 530,
  },
];

export default books;
